import { cleanText } from "../library/normalization.js";

export const FLIPBOOK_THEME_OPTIONS = [
  {
    id: "paper-cream",
    label: "Paper Cream",
    stageBackground: "#ffffff",
    stageSurface: "none",
    stageGlow: "transparent",
    pageBackground: "#f3e8d4",
    pageText: "#2d2318",
    pageMuted: "#7b6a56",
    pageBorder: "rgba(94, 71, 44, 0.24)",
    pageChromeText: "rgba(44, 33, 21, 0.64)",
    pageChromeLine: "rgba(82, 61, 35, 0.14)",
    toolbarBackground: "#e8f0ff",
    toolbarBorder: "#103474",
    toolbarText: "#103474",
    stageHeaderBackground: "#ffffff",
    stageHeaderBorder: "#d5e3ff",
    stageHeaderText: "#103474",
  },
  {
    id: "soft-white",
    label: "Soft White",
    stageBackground: "#ffffff",
    stageSurface: "none",
    stageGlow: "transparent",
    pageBackground: "#f7f6f1",
    pageText: "#1c2229",
    pageMuted: "#68737e",
    pageBorder: "rgba(82, 101, 122, 0.18)",
    pageChromeText: "rgba(37, 49, 60, 0.58)",
    pageChromeLine: "rgba(82, 101, 122, 0.14)",
    toolbarBackground: "#e8f0ff",
    toolbarBorder: "#103474",
    toolbarText: "#103474",
    stageHeaderBackground: "#ffffff",
    stageHeaderBorder: "#d5e3ff",
    stageHeaderText: "#103474",
  },
  {
    id: "warm-gray",
    label: "Warm Gray",
    stageBackground: "#ffffff",
    stageSurface: "none",
    stageGlow: "transparent",
    pageBackground: "#efede7",
    pageText: "#24211d",
    pageMuted: "#6d665d",
    pageBorder: "rgba(104, 95, 84, 0.18)",
    pageChromeText: "rgba(56, 50, 44, 0.58)",
    pageChromeLine: "rgba(104, 95, 84, 0.14)",
    toolbarBackground: "#e8f0ff",
    toolbarBorder: "#103474",
    toolbarText: "#103474",
    stageHeaderBackground: "#ffffff",
    stageHeaderBorder: "#d5e3ff",
    stageHeaderText: "#103474",
  },
  {
    id: "dark-sepia",
    label: "Dark Sepia",
    stageBackground: "#ffffff",
    stageSurface: "none",
    stageGlow: "transparent",
    pageBackground: "#d9c3a5",
    pageText: "#281b12",
    pageMuted: "#6c5541",
    pageBorder: "rgba(88, 60, 34, 0.24)",
    pageChromeText: "rgba(44, 29, 19, 0.62)",
    pageChromeLine: "rgba(88, 60, 34, 0.15)",
    toolbarBackground: "#e8f0ff",
    toolbarBorder: "#103474",
    toolbarText: "#103474",
    stageHeaderBackground: "#ffffff",
    stageHeaderBorder: "#d5e3ff",
    stageHeaderText: "#103474",
  },
];

const THEME_MAP = new Map(FLIPBOOK_THEME_OPTIONS.map((theme) => [theme.id, theme]));

export function resolveFlipbookTheme(themeId = "") {
  return THEME_MAP.get(cleanText(themeId).toLowerCase()) || FLIPBOOK_THEME_OPTIONS[0];
}
