-- Recommended tables for running this bot on Supabase/Postgres.
-- If your virtual classroom already has a users table, reuse it and set the
-- USERS_* env vars to match its actual table and column names.

create table if not exists public.preguntas (
    id bigint generated by default as identity primary key,
    tema text not null,
    pregunta text not null,
    respuesta_correcta text not null,
    respuesta_incorrecta1 text not null,
    respuesta_incorrecta2 text not null,
    respuesta_incorrecta3 text not null,
    razon text,
    unique (pregunta)
);

create table if not exists public.puntaje (
    user_id bigint primary key,
    respuestas_correctas integer not null default 0,
    respuestas_incorrectas integer not null default 0,
    veces_jugadas integer not null default 0,
    puntaje_promedio double precision not null default 0
);

-- Example only. If your classroom project already owns this table, do not create
-- a duplicate. Instead point USERS_TABLE and USERS_*_COLUMN at the existing table.
create table if not exists public.users (
    id uuid primary key default gen_random_uuid(),
    email text not null,
    discord_id text,
    course_name text not null
);
